//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fooodEntities : DbContext
    {
        public fooodEntities()
            : base("name=fooodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

            modelBuilder.Entity<Food_Size>()
                           .HasMany(x => x.Food_Dish)
                           .WithRequired(x => x.Food_Size)
                           .HasForeignKey(x => x.SizeId);

            modelBuilder.Entity<Food_Type>()
                .HasMany(x => x.Food_Dish)
                .WithRequired(x => x.Food_Type)
                .HasForeignKey(x => x.TypeId);
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<CusOrder> CusOrders { get; set; }
        public virtual DbSet<Food_Dish> Food_Dish { get; set; }
        public virtual DbSet<Food_Size> Food_Size { get; set; }
        public virtual DbSet<Food_Type> Food_Type { get; set; }
        public virtual DbSet<OrderHistory> OrderHistorys { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
    }
}
