//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public int Id { get; set; }
        public string name { get; set; }
        public double price { get; set; }
        public int numberDish { get; set; }
        public System.DateTime dateOrder { get; set; }
    }
}
